//! Embedded-kernel registry: the example kernels' PTX, compiled into the
//! zoxide binary at build time (build.zig `-Dembed-kernels`, default on),
//! so `zoxide run vector_add` / `zoxide bench hgemm_bf16` work with no
//! kernels/ directory alongside the binary.
//!
//! This module holds the pure lookup logic (unit-tested here); the table
//! itself is generated by build.zig and imported as `embedded_kernels`.
//!
//! Resolution order in the CLI is: an explicit path that exists wins;
//! otherwise a bare kernel name (no path separator, extension optional)
//! resolves against this table. Anything with a path separator that does
//! not exist stays a plain "file not found" — silently falling back to an
//! embedded kernel for a typo'd path would run the wrong code convincingly.

const std = @import("std");

pub const Entry = struct { stem: []const u8, ptx: [:0]const u8 };

/// Normalize a CLI input to a lookup stem: extension stripped, and only when
/// it is a bare name. Returns null for anything path-shaped.
pub fn stemOf(input: []const u8) ?[]const u8 {
    if (input.len == 0) return null;
    if (std.mem.indexOfScalar(u8, input, '/') != null) return null;
    if (std.mem.indexOfScalar(u8, input, '\\') != null) return null;
    const stem = std.fs.path.stem(input);
    if (stem.len == 0) return null;
    return stem;
}

/// Find a kernel by stem. Returns its embedded PTX text. Generic over the
/// table's entry type: the generated registry module defines its own Entry
/// struct (a named import here would put embedded.zig in two modules of the
/// exe compilation — the same clash the launch-bounds abi design avoided).
pub fn lookup(kernels: anytype, stem: []const u8) ?@TypeOf(kernels[0].ptx) {
    for (kernels) |k| {
        if (std.mem.eql(u8, k.stem, stem)) return k.ptx;
    }
    return null;
}

/// Available stems, for error messages. Caller owns the slice.
pub fn stems(gpa: std.mem.Allocator, kernels: anytype) ![][]const u8 {
    const out = try gpa.alloc([]const u8, kernels.len);
    for (kernels, 0..) |k, i| out[i] = k.stem;
    return out;
}

test "stemOf: bare names only, extension stripped" {
    try std.testing.expectEqualStrings("vector_add", stemOf("vector_add").?);
    try std.testing.expectEqualStrings("vector_add", stemOf("vector_add.ptx").?);
    try std.testing.expectEqualStrings("vector_add", stemOf("vector_add.cubin").?);
    // Paths never hit the embedded table — a typo'd path must not silently
    // run a different kernel.
    try std.testing.expect(stemOf("kernels/vector_add.ptx") == null);
    try std.testing.expect(stemOf("./vector_add.ptx") == null);
    try std.testing.expect(stemOf("") == null);
}

test "lookup finds by stem and nothing else" {
    const table = [_]Entry{
        .{ .stem = "alpha", .ptx = "// a" },
        .{ .stem = "beta", .ptx = "// b" },
    };
    try std.testing.expectEqualStrings("// a", lookup(&table, "alpha").?);
    try std.testing.expect(lookup(&table, "gamma") == null);
    try std.testing.expect(lookup(&table, "") == null);
}
